# Generated by Django 3.2 on 2023-05-14 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_user_confirmation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='user', max_length=9, verbose_name='Роль'),
        ),
    ]
