# Generated by Django 3.2 on 2023-05-14 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, default='Описание отсутсвует', max_length=256, verbose_name='Биография'),
        ),
    ]
