# Generated by Django 3.2 on 2023-02-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0012_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.SlugField(help_text='Введите имя пользователя', max_length=150, unique=True, verbose_name='Пользователь'),
        ),
    ]
