# Generated by Django 3.2 on 2023-04-16 10:30

from django.db import migrations, models
import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0016_auto_20230213_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(help_text='Год выхода', null=True, validators=[reviews.validators.check_future_year], verbose_name='Год создания'),
        ),
    ]
