# Generated by Django 3.2 on 2023-05-13 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20220120_0209'),
        ('reviews', '0017_alter_title_year'),
    ]

    operations = [
    ]
