# Generated by Django 3.2 on 2023-05-19 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0020_auto_20230519_2315'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
