# Generated by Django 3.2 on 2023-05-20 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0024_auto_20230520_0005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='genres',
            new_name='genre',
        ),
    ]
