# Generated by Django 3.2 on 2023-05-20 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0025_rename_genres_title_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='genre',
            new_name='genres',
        ),
    ]
