# Generated by Django 3.2 on 2023-05-20 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0028_auto_20230520_1812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='genres',
            new_name='genre',
        ),
    ]
